"""disabling is activev User & setting default to is_active

Revision ID: 46c7e7ed8852
Revises: 1cd75eb3427d
Create Date: 2022-11-24 14:35:52.855424

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46c7e7ed8852'
down_revision = '1cd75eb3427d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_email_verified', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'is_email_verified')
    # ### end Alembic commands ###
