"""commenting pwd

Revision ID: 985786ffee8f
Revises: fceafda23fb2
Create Date: 2022-11-24 14:46:33.313572

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '985786ffee8f'
down_revision = 'fceafda23fb2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', mysql.VARCHAR(length=100), nullable=False))
    # ### end Alembic commands ###
