"""setting columns as nullable

Revision ID: 9cc651193d6b
Revises: d8189b6f6eab
Create Date: 2022-11-24 14:29:02.509391

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9cc651193d6b'
down_revision = 'd8189b6f6eab'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('address', 'user_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('address', 'street',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.alter_column('address', 'city',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.alter_column('address', 'state',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.alter_column('address', 'country',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.alter_column('address', 'postcode',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('address', 'postcode',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.alter_column('address', 'country',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.alter_column('address', 'state',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.alter_column('address', 'city',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.alter_column('address', 'street',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.alter_column('address', 'user_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
