"""change address table fields logic


Revision ID: c40d136cb4af
Revises: bc7d3fd14654
Create Date: 2022-12-07 16:22:22.537416

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c40d136cb4af'
down_revision = 'bc7d3fd14654'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('address', sa.Column('address_1', sa.String(length=100), nullable=True))
    op.add_column('address', sa.Column('address_2', sa.String(length=100), nullable=True))
    op.add_column('address', sa.Column('town_city', sa.String(length=100), nullable=True))
    op.add_column('address', sa.Column('county', sa.String(length=100), nullable=True))
    op.drop_column('address', 'street')
    op.drop_column('address', 'state')
    op.drop_column('address', 'country')
    op.drop_column('address', 'city')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('address', sa.Column('city', mysql.VARCHAR(length=100), nullable=True))
    op.add_column('address', sa.Column('country', mysql.VARCHAR(length=100), nullable=True))
    op.add_column('address', sa.Column('state', mysql.VARCHAR(length=100), nullable=True))
    op.add_column('address', sa.Column('street', mysql.VARCHAR(length=100), nullable=True))
    op.drop_column('address', 'county')
    op.drop_column('address', 'town_city')
    op.drop_column('address', 'address_2')
    op.drop_column('address', 'address_1')
    # ### end Alembic commands ###
