"""removes remaining nullable

Revision ID: fceafda23fb2
Revises: 46c7e7ed8852
Create Date: 2022-11-24 14:40:53.879191

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fceafda23fb2'
down_revision = '46c7e7ed8852'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('contact', 'user_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('contact', 'phone',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.alter_column('contact', 'email',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.alter_column('personal_data', 'user_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('personal_data', 'first_name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.alter_column('personal_data', 'last_name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.alter_column('personal_data', 'dob',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('reset_password', 'user_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('reset_password', 'token',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.alter_column('reset_password', 'expires_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('reset_password', 'is_used',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reset_password', 'is_used',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    op.alter_column('reset_password', 'expires_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('reset_password', 'token',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.alter_column('reset_password', 'user_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('personal_data', 'dob',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('personal_data', 'last_name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.alter_column('personal_data', 'first_name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.alter_column('personal_data', 'user_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('contact', 'email',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.alter_column('contact', 'phone',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.alter_column('contact', 'user_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
